# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/ECE520/Project/UART/UART.srcs/sources_1/bd/UART_design/ip/UART_design_processing_system7_0_0/UART_design_processing_system7_0_0.xci
# IP: The module: 'UART_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ECE520/Project/UART/UART.gen/sources_1/bd/UART_design/ip/UART_design_processing_system7_0_0/UART_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/ECE520/Project/UART/UART.srcs/sources_1/bd/UART_design/ip/UART_design_processing_system7_0_0/UART_design_processing_system7_0_0.xci
# IP: The module: 'UART_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ECE520/Project/UART/UART.gen/sources_1/bd/UART_design/ip/UART_design_processing_system7_0_0/UART_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
