# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/UART_design/UART_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_design || ORIG_REF_NAME==UART_design} -quiet] -quiet

# IP: bd/UART_design/ip/UART_design_processing_system7_0_0/UART_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_design_processing_system7_0_0 || ORIG_REF_NAME==UART_design_processing_system7_0_0} -quiet] -quiet

# XDC: c:/ECE520/Project/UART/UART.gen/sources_1/bd/UART_design/UART_design_ooc.xdc
